### ISSUE TITLE
dockerize the app using Dockerfile and docker-compose.yml

### ISSUE THREAD

**Issue by thevivekshukla** [thevivekshukla/django-expensor#5]
Make sure to add following services to the Docker:

- PostgreSQL
- Celery
 - Celery beat

**Comment by Zoxon470** [comment]
I can implement your task, just waiting for.

**Comment by zjesko** [comment]
working on it right now

**Comment by Zoxon470** [comment]
@akshatcx I have already completed 80% of the task

**Comment by Zoxon470** [comment]
@thevivekshukla I have done this task. Check, please https://github.com/thevivekshukla/django-expensor/pull/8

**Comment by thevivekshukla** [comment]
#8 this closes the issues. Thanks @Zoxon470
